### ISSUE TITLE
Testify suite support

### ISSUE THREAD

**Issue by othalla** [leoluz/nvim-dap-go#1]
Hello,

I tried the module with test suite and it retrieves the name of the suite, not the subtest.
Its quite problematic as a suite can contain lots of subtests and it does not provide a way to execute a specific context.

What do you think about adding it ?

**Comment by leoluz** [comment]
Not sure if I understand what you mean by "execute a specific context " but if you want to debug just a specific subtest you can run `:lua require('dap-go').debug_test()`. It will find the nearest test from the current cursor position and start a debug session just for that.
Is this what you want?

**Comment by othalla** [comment]
By context I meant the subtest of a testify suite.

I tried it and I think I got an error.
I'll try to add some example here.

**Comment by leoluz** [comment]
How many levels of subtests do you have? I constantly debug testify test with one subtest and it works. I know that there is a limitation if you have more than 2 levels of subtests. I already have a patch to fix this btw. I just need to find time to apply it. Will let you know when I do it.
