### ISSUE TITLE
ENOENT on debug_test() exec

### ISSUE THREAD

**Issue by inievaMeLi** [leoluz/nvim-dap-go#10]
Hi. First of all, i love this plugin.
It upgraded my neovim go development workflow to the next level.

So, going to the issue, i'm using AstroNvim distro, and added nvim-dap-go as i used to. But this time i'm using a new m1 macbook pro.
I installed go, dlv, and went straight to the testing of the dap.
At the moment of starting the debug session i found this error message, which is triggered by an assertion in the source from the plugin.

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/53837273/172068511-8ee00bea-1bfc-4274-9901-02ae2292b710.png">

I would appreciate any guidance or hint to have it running business as usual.
Thank you in advance 😄 .

**Comment by leoluz** [comment]
Hey thank you and so sorry about the delay.
Are you sure you have dlv in your path? The error message seems to complain about not being able to find the dlv binary.

**Comment by leoluz** [comment]
closing this for now. Please feel free to reopen if you think this is a real issue with nvim-dap-go
