### ISSUE TITLE
Configuration file for reading program specific arguments

### ISSUE THREAD

**Issue by shatoboar** [leoluz/nvim-dap-go#14]
Hi, is there a way to configure something like a launch.json file, where we can set the environmental variables and program arguments for debugging the main function?

**Comment by freddiehaddad** [comment]
I created a PR that will prompt the user for command-line arguments.  It would be just as easy to add another option to load the arguments from a file.  Curious if the author will accept it.  I tested and it works fine.  It's a naive implementation and could use some hardening.  But not even sure if the author will accept it.

https://github.com/leoluz/nvim-dap-go/pull/15

**Comment by freddiehaddad** [comment]
In the meantime, you can use my forked repo. If the author rejects my PR, then I'll just keep maintaining it myself since this a feature I need.

https://github.com/freddiehaddad/nvim-dap-go

**Comment by leoluz** [comment]
implemented in #15
