### ISSUE TITLE
Wrong working directory, not using Go workspaces

### ISSUE THREAD

**Issue by maxlandon** [leoluz/nvim-dap-go#16]
Hello,

Trying to set up and test this plugin, I'm facing an issue: I cannot start a debug session.

## Steps
- Install the plugin and initialize it as usual with `require('dap-go').setup()`
- Toggle a breakpoint in my main function.
- Start a debug session (choose '1' when prompted for the type of debug to start)

## Errors
Neovim immediately notifies: 'Error on launch: Failed to launch'
The `dap-repl` buffer also contains the following output:
```
Build Error: go build -o /home/user/__debug_bin -gcflags all=-N -l /home/user/code/github.com/maxlandon/sflags/examples/gcomps/main.go
code/github.com/maxlandon/sflags/examples/gcomps/main.go:4:2: cannot find package "github.com/octago/sflags/gen/gcobra" in any of:
	/usr/local/go/src/github.com/octago/sflags/gen/gcobra (from $GOROOT)
	/home/user/go/src/github.com/octago/sflags/gen/gcobra (from $GOPATH)
code/github.com/maxlandon/sflags/examples/gcomps/main.go:5:2: cannot find package "github.com/octago/sflags/gen/gcomp" in any of:
	/usr/local/go/src/github.com/octago/sflags/gen/gcomp (from $GOROOT)
	/home/user/go/src/github.com/octago/sflags/gen/gcomp (from $GOPATH) (exit status 1)
```

## Clues on the reasons for this error
I notice that, based on the above output:
- `nvim-dap-go` generates the debug binary from my $HOME working directory (thus `/home/user/__debug_bin`), which is both outside my Go module AND outside my go.work file (which path is `/home/user/code/go.work`)
- Also note that I have no problems compiling my program on its own, as well as with `dlv`, mentionned below.

## Other tests
- I've tried running dlv in my Go module (more precisely, in the package of my `main()` function, which is `~/code/github.com/maxlandon/sflags/examples/gcomps`), with the following command:
```
dlv debug --headless --api-version 2 --accept-multiclient .
```
- Note that this command succeeds in building AND running the `__debug_bin` in my main package, but when starting the debug session and choosing `4 - Attach` then choosing the corresponding process, Neovim throws `Error on attach: failed to attach`. I don't know why, but it's likely that I'm not passing the correct flags to my `dlv` command. Just mentioning for the sake of adding details.

## Interpretation
It seems to me that this plugin is not using the correct working directory to start the `dlv` process, thus not resulting in this error.
- I would be really happy to help fixing this, and I've checked this plugin's code, but I'm not familiar with the Lua APIs to launch processes: I could not find where to specify a working directory.
- Added to that, I suspect that it would be better to use some of the Neovim/LSP stuff for this, as they automatically define a Neovim workspace based on default/specified patterns (e.g `.git`, `go.work`, etc).

Looking forward to a fix or some clues to do it !
Thanks a lot !

**Comment by leoluz** [comment]
What happens if you run?

```
cd /home/user/code/github.com/maxlandon/sflags/examples/gcomps
go build main.go
```

Are you running a gomod project? From your path it looks like you are using the old gopath approach. 

What is the output of:

```
echo $GOPATH
```

**Comment by maxlandon** [comment]
Hello,
Well you had the right intuition:
I had an `export GOPATH=$(go env GOPATH)` still hanging around in my `.bashrc` file.
So to those who face the same issue, look at your dotfiles: you might have forgotten to remove Go settings from the old times, which are not needed anymore.
Thanks a lot for the hint.
