### ISSUE TITLE
Feature: debug_nearest_or_last_test()

### ISSUE THREAD

**Issue by marcomayer** [leoluz/nvim-dap-go#17]
After debugging a test (that's usually failing), I often find myself in code outside of the actual test file setting a new breakpoint for example. Now I'd like to debug the last run test again without having to navigate back to the test file/function to start debug_test().

For this it would be great to have a new function (or extend the old one) to debug the test that was last run if no nearest test was found. From a first glance implementation should be rather simple, maybe I'll find sometime to do a PR myself later this week.

**Comment by leoluz** [comment]
I like the idea! Let's make it happen! :)

**Comment by leoluz** [comment]
implemented in. #21
