### ISSUE TITLE
Option to debug a package with arguments

### ISSUE THREAD

**Issue by maxlandon** [leoluz/nvim-dap-go#20]
Coming back with more or less of a feature request/enhancement.

Currently, there is only a way to debug a single file with arguments.
However, when a main package contains more than one file, and that it also declares CLI functionality (commands),
we need to both be able to compile the entire package, and to pass some arguments to the program.
My hack fix was to duplicate/add the following snippet:
```
        {
            type = "go",
            name = "Debug Package (Arguments)",
            request = "launch",
            program = "${fileDirname}",
            args = get_arguments,
        },
```

Simply adding this snippet in `setup_go_configuration(dap)` works fine.
Thanks !

**Comment by leoluz** [comment]
Latest version allows you to provide additional dap configuration from the setup function. Please check the documentation for more details.
