### ISSUE TITLE
[help] How to set timeouts?

### ISSUE THREAD

**Issue by bravoecho** [leoluz/nvim-dap-go#22]
Hi,
Is there a way to pass the `initialize_timeout_sec` and `disconnect_timeout_sec` options (<https://github.com/mfussenegger/nvim-dap/blob/61643680dcb771a29073cd432894e2f81a7c2ae3/doc/dap.txt#L134>) to the Go debugger?
Thank you! 🙂

**Comment by leoluz** [comment]
Hi @bravoecho!
You can configure `nvim-dap` independently from `nvim-dap-go`. All `nvim-dap` configurations will be honored by the time the debugger starts.
