### ISSUE TITLE
connecting to remote headless DAP no longer working

### ISSUE THREAD

**Issue by marcomayer** [leoluz/nvim-dap-go#27]
The changes in https://github.com/leoluz/nvim-dap-go/commit/bd9823da22165ea4aa7ec232e8c3a9b3158e017a break the remote debugging for me. I added the remote adapter to the new dap_configurations, and after starting the debugger:

`dlv debug -l 127.0.0.1:38697 --api-version 2 --headless ./cmd/main.go`

I get "Error on attach: Failed to attach: no debugger found". Reverting back to commit 0cc173c8, it's all fine again.

**Comment by leoluz** [comment]
I suspect it might be related with the port. It is automatically assigned to a free port now. Make sure to inspect the process to get the correct port it is listening to.

**Comment by leoluz** [comment]
@marcomayer please confirm if the port is really your issue. 
I created a PR to allow setting up the port in the user config:
https://github.com/leoluz/nvim-dap-go/pull/28

**Comment by marcomayer** [comment]
@leoluz thanks a lot, that solves it! 🎄 🎅
