### ISSUE TITLE
How to wait for user input?

### ISSUE THREAD

**Issue by da-the-dev** [leoluz/nvim-dap-go#31]
I'm learning go and I write simple standard i/o programs. Here's some code:
```go
package main

import (
	"fmt"
	"math"
	"bufio"
	"os"
	"strconv"
	"strings"
)

func main() {
	reader := bufio.NewReader(os.Stdin)

*	var repeatAmount int
	fmt.Fscanf(reader, "%d\n", &repeatAmount)

	for i := 0; i < repeatAmount; i++ {
		var numberOfProgs int
		fmt.Fscanf(reader, "%d\n", &numberOfProgs)
. . .
```
I use lunarvim, which has nvim-dap and nvim-dap-ui preconfigured. I have installed and configured nvim-dap-go to add golang debugger configuration. If I place a breakpoint on a line marked with "\*" and start debugging, the debugger skips over the `fmt.Fscanf()` and goes somewhere deep into golang's source code.  It does not wait for user input and I assume the reason is it doesn't have any terminal to take user input from. How can I configure my settings so that the debugger would wait for user input? 

![image](https://user-images.githubusercontent.com/39898616/213135985-958b1216-a48d-4486-b0cb-89c3cee12dda.png)

**Comment by leoluz** [comment]
You can run the program in the terminal and attach (option 4) to the running process selecting the correct pid.
