### ISSUE TITLE
Remote configuration does not work?

### ISSUE THREAD

**Issue by ihgann** [leoluz/nvim-dap-go#34]
It appears the code added in https://github.com/leoluz/nvim-dap-go/commit/c75921726ccfe97070285f206de49eddff276ea5 has recently been removed in https://github.com/leoluz/nvim-dap-go/commit/bd9823da22165ea4aa7ec232e8c3a9b3158e017a.

Because of this, it seems the steps in the README to add a remote adapter no longer work (as of the latest CLN - https://github.com/leoluz/nvim-dap-go/commit/6f045a72a05a78e4071dd0880f08214a2bb1461b.

Is there something else we need to do in `nvim-dap` configuration to get this working now? It was working prior to my updating of this branch.

**Comment by leoluz** [comment]
I am not sure what you are trying to do but the [README documentation](https://github.com/leoluz/nvim-dap-go#configuring) to add a configuration to debug remotely  does work. The links that you posted are related to a refactoring that impacted while running dap in headless mode. Please see this issue: https://github.com/leoluz/nvim-dap-go/issues/27.
Hope it helps.

**Comment by ihgann** [comment]
I tested with the port, and that resolved it for me as well. Thanks!

Dup of #27.
