### ISSUE TITLE
Can't launch dap when multiple go files in main package, Error on launch: Failed to launch

### ISSUE THREAD

**Issue by LugeKit** [leoluz/nvim-dap-go#41]
I can not launch dap when the main package contains multiple files, it shows `Error on launch: Failed to launch`. If I just move them into sub directory and only leave main.go in package main, I can start dap.
However, I can simply run dlv in command line, which means that dlv supports debug a main package with multiple files in. So how can I use dap-go to achieve this?
This is my configuration for dap:
```lua
-- language configuration
require("dap-go").setup({})

-- ui configuration
local dapui = require("dapui")
dapui.setup({})

local dap = require("dap")
dap.listeners.after.event_initialized["dapui_config"] = function()
    dapui.open()
end
dap.listeners.before.event_terminated["dapui_config"] = function()
    dapui.close()
end
dap.listeners.before.event_exited["dapui_config"] = function()
    dapui.close()
end
```
More Info:
- Both `Linux Mint 21.3` and `MacOS intel Ventura 13.2.1` have this problem
- Nvim version: `NVIM v0.9.0-dev-1296+g8b7fb668e`
- dlv version: `1.20.1`
- go version: `go1.19 darwin/amd64`

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/43108396/229688815-05460406-4cf8-477d-bcfa-73f357bde1fa.png">

**Comment by LugeKit** [comment]
I have figured out why...I should use debug with package instead.

**Comment by piraz** [comment]
Love you so much @LugeKit. That helped me a lot!

What about to put that information in the README.md?

**Comment by mpas** [comment]
I seem to have the same issue. I have 2 files in my local folder and am unable to start the debugger. This even with the package option.
