### ISSUE TITLE
plugin not able to start delve and error dap not installed

### ISSUE THREAD

**Issue by ehrktia** [leoluz/nvim-dap-go#49]
installed the dap client
`use 'mfussenegger/nvim-dap'`
followed dap installation wiki for golang using delve directly
https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#go-using-delve-directly
based on instructions from the wiki installed` use 'leoluz/nvim-dap-go'`
as per readme from the plugin to start delve
`require('dap-go').setup()`
added to `dap.lua` file and sourced it via `init.lua`
setup details:
init.lua ->dap.lua
error:
```
Error detected while processing /home/karthick/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...e/nvim/site/pack/packer/start/nvim-dap-go/lua/dap-go.lua:38: dap-go dependency error: dap not installed
```

checked command by executing  `:DapContinue` the command is available

nvim version:

```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by leoluz** [comment]
For some reason the command `require('dap')` is failing in your setup. Try running `:lua require('dap')` and see if it returns error. If it does, double check your configurations.
