### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by kaleaht** [leoluz/nvim-dap-go#5]
I  have the following line in my vimrc:
```lua require('dap-go').setup()```

Versions:
NVIM v0.7.0-dev
Delve Debugger
Version: 1.8.2

At startup i get the following error message:
```
E5108: Error executing lua .../dap-go.nvim/lua/dap-go.lua:127: attempt to index local 'options' (a nil value)
stack traceback:
        /home/ahti/dotfiles/plugged/dap-go.nvim/lua/dap-go.lua:127: in function 'setup'
        [string ":lua"]:1: in main chunk
```
Is my config wrong or is this a bug?

**Comment by leoluz** [comment]
I am still using nvim-0.6.1 and this could be a compatibility issue. Not sure.

However this error message is strange as Im not sure how `dap-go` could complain about that line (127). Are you running the latest `dap-go` version? What is the output of the following command?
```
sed '125,130!d' /home/ahti/dotfiles/plugged/dap-go.nvim/lua/dap-go.lua
```

**Comment by leoluz** [comment]
Oh.. I see what the problem is. The error you are getting is not from this plugin (`nvim-dap-go`) but from this one:
https://github.com/yriveiro/dap-go.nvim/
I knew this name would confuse someone someday. 😅
