### ISSUE TITLE
parse function not found for treesitter

### ISSUE THREAD

**Issue by dexianta** [leoluz/nvim-dap-go#51]
I've been using it without issues, but since recently I ran `PackerSync`, I'm unable to call `debug_test`, got the following error message.

```
E5108: Error executing lua ...e/nvim/site/pack/packer/start/nvim-dap-go/lua/dap-go.lua:203: attempt to call field 'parse' (a nil value)
stack traceback:
        ...e/nvim/site/pack/packer/start/nvim-dap-go/lua/dap-go.lua:203: in function 'get_closest_test'
        ...e/nvim/site/pack/packer/start/nvim-dap-go/lua/dap-go.lua:253: in function 'debug_test'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

for the newest treesitter, I think the function has been renamed to `parse_query` (line 203 and 220), after manually changed the code locally, it runs without problem

https://github.com/leoluz/nvim-dap-go/blob/cdf604a5703838f65fdee7c198f6cb59b563ef6f/lua/dap-go.lua#L203-L220

happy to make a small PR if deemed appropriate

**Comment by leoluz** [comment]
Hey, thanks for the investigation. If you can push a PR, it will be awesome as I'm far from my laptop for the next few weeks.

**Comment by leoluz** [comment]
Actually it is the opposite. The `parse_query` is the deprecated function. 
```
vim.treesitter.query.parse_query() is deprecated, use vim.treesitter.query.parse() instead
. :help deprecated
This feature will be removed in Nvim version 0.10
stack traceback:
        ...im/0.9.1/share/nvim/runtime/lua/vim/treesitter/query.lua:230: in function 'pars
e_query'
        ...e/nvim/site/pack/packer/start/nvim-dap-go/lua/dap-go.lua:213: in function 'get_
closest_test'
        ...e/nvim/site/pack/packer/start/nvim-dap-go/lua/dap-go.lua:263: in function <...e
/nvim/site/pack/packer/start/nvim-dap-go/lua/dap-go.lua:262>
```
You are getting the error because you probably using an old version of nvim.
