### ISSUE TITLE
debug_test() will potentially execute multiple tests 

### ISSUE THREAD

**Issue by ddomurad** [leoluz/nvim-dap-go#55]
First of all, Hello :) This is a grate simple plugin, thank you for developing it ! I'm not sure if this is a bug, or intended behavior. 

Given a test file: 
```go
func Test_SimpleTest(t *testing.T) {
	fmt.Println("Test_SimpleTest")
}

func Test_SimpleTest_SpecialCase(t *testing.T) {
	fmt.Println("Test_SimpleTest_SpecialCase")
}

func Test_OtherSimpleTest(t *testing.T) {
	fmt.Println("Test_OtherSimpleTest")
}
```
Running `lua require('dap-go').debug_test()` on  `Test_SimpleTest` will execute  `Test_SimpleTest` and `Test_SimpleTest_SpecialCase`. 

REPL output:
```
Type 'dlv help' for list of commands.

[debug-adapter stdout] Test_SimpleTest

[debug-adapter stdout] Test_SimpleTest_SpecialCase
PASS
```

This happens because the `-test.run` arguments value is passed as plain name (in this case `Test_SimpleTest`) and dlv will match all tests in the file that contain this substring in their names. 

Possible fix:
Add regex line anchors to the `-test.run` argument value. 

```go
local function debug_test(testname, testpath, build_flags)
  local dap = load_module("dap")
  dap.run({
    type = "go",
    name = testname,
    request = "launch",
    mode = "test",
    program = testpath,
    args = { "-test.run", "^" .. testname .. "$" },
    buildFlags = build_flags,
  })
end
```

**Comment by leoluz** [comment]
Hey! Thank you!
That is a good point. Have you tried the proposed solution to make sure it works?

**Comment by ddomurad** [comment]
@leoluz Yes I have :)  Here is my analysis.

For given test samples: 
```go
func Test_SimpleTest_Nested(t *testing.T) {
	t.Run("example", func(t *testing.T) {
		fmt.Println("Test_NestedTest_example")
	})

	t.Run("example 1", func(t *testing.T) {
		fmt.Println("Test_NestedTest_example 1")
	})

	t.Run("example 2", func(t *testing.T) {
		fmt.Println("Test_NestedTest_example 2")

		t.Run("example 2.1", func(t *testing.T) {
			fmt.Println("Test_NestedTest_example 2.1")
		})
	})
}

func Test_SimpleTest(t *testing.T) {
	fmt.Println("Test_SimpleTest")
}

func Test_SimpleTest_SpecialCase(t *testing.T) {
	fmt.Println("Test_SimpleTest_SpecialCase")
}

func Test_OtherSimpleTest(t *testing.T) {
	fmt.Println("Test_OtherSimpleTest")
}
```

The current algorithm will generate following test name passed to dlv:
```
Test_SimpleTest_Nested
Test_SimpleTest_Nested/example
Test_SimpleTest_Nested/example_1
Test_SimpleTest_Nested/example_2
example_2/example_2.1
Test_SimpleTest
Test_SimpleTest_SpecialCase
Test_OtherSimpleTest
```
We can observe that without the line anchors `Test_SimpleTest` and `Test_SimpleTest_Nested/example`   will also trigger execution of other tests.
`Test_SimpleTest -> Test_SimpleTest, Test_SimpleTest_Nested and Test_SimpleTest_SpecialCase`
`Test_SimpleTest_Nested/example -> Test_SimpleTest_Nested/example, Test_SimpleTest_Nested/example_1 and Test_SimpleTest_Nested/example_2`

And ofc `example_2/example_2.1` does not work and wont result in any test being executed. 

I have tested the proposed solution on all the cases, and it seems to work just fine.  (ofc except of the `example_2/example_2.1` case)

Off-topic: 
I have also noticed that `nvim-dap-go` currently won't execute single testify suite test methods, only the whole suite. I will crate a separate issue describing the problem.

**Comment by leoluz** [comment]
The main issue is now fixed in https://github.com/leoluz/nvim-dap-go/commit/1b508e9db330108d3b5d62a6d9cc01fe6bbdd4e0 .

The `example_2/example_2.1` case is a known issue (https://github.com/leoluz/nvim-dap-go/issues/39)

Thank you for the great details in your issue.
