### ISSUE TITLE
There is some way to debug without compiling?

### ISSUE THREAD

**Issue by Zeioth** [leoluz/nvim-dap-go#56]
Let's say I already have an executable compiled in debug mode. There is some way I can just run it with nvim-dap-go skipping the compiling step?

The compilation nvim-dap-go try to do seems to only work correctly with single file programs. If the program has more than one file, the compilation will fail, as it only take the current file.

My config is just

```
require('dap-go').setup()
```

And then running `DapContiue`.

**Comment by Zeioth** [comment]
You can test it by trying to debug this multi-file hello world program:

main.go
```go
// main.go

package main

import "fmt"

func main() {
    msg := getMessage() // Calling the function from "helper.go"
    fmt.Println(msg)
}
```

helpter.go
```go
// helper.go

package main

func getMessage() string {
    return "Hello, World!"
}
```

**Comment by Zeioth** [comment]
Ok after further research this is my solution:

```lua
      -- Go
      -- Requires:
      -- * The system dependency 'dlv'
      -- * Change the line "command = '/usr/bin/dlv'" to your actual dlv path.
      -- * You to :cd your project before running :DapContinue
      -- * Your project has been initialized with 'go mod init module_name'
      -- note that no mason package is required.
      dap.adapters.delve = {
        type = 'server',
        port = '${port}',
        executable = {
          command = '/usr/bin/dlv',
          args = {'dap', '-l', '127.0.0.1:${port}'},
        }
      }
      dap.configurations.go = {
        {
          type = "delve",
          name = "Compile module and debug this file",
          request = "launch",
          program = "./${relativeFileDirname}",
        },
        {
          type = "delve",
          name = "Compile module and debug this test file",
          request = "launch",
          mode = "test",
          program = "${file}"
        },
        {
          type = "delve",
          name = "Compile module and debug this test go.mod",
          request = "launch",
          mode = "test",
          program = "./${relativeFileDirname}"
        }
      }
```

As described [here](https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv_dap.md) dlv has a `dlv exec` mode, but one can only use it manually. And in order to use dlv with DAP one must run it as `dlv dap`.

In other words, there is no way to avoid compiling the module when running a test.

The solution I've posted is the equivalent of running `debug package` when using `lua require('dap-go').setup()`.

**Comment by leoluz** [comment]
> Let's say I already have an executable compiled in debug mode. There is some way I can just run it with nvim-dap-go skipping the compiling step?

Yes. However I don't understand what you mean by executable compiled in debug mode. Compiling is one thing and debugging a running process is a different thing. You can run your executable and attach a debug session to the running process. In this case there is no additional compilation involved.

> The compilation nvim-dap-go try to do seems to only work correctly with single file programs. If the program has more than one file, the compilation will fail, as it only take the current file.

I am able to debug programs with thousand of files. The error that you are having is not related to having multiple files in your application's source.

Feel free to reopen the issue if your problem remains.
