### ISSUE TITLE
Feature request: "envFile" attribute

### ISSUE THREAD

**Issue by niklod** [leoluz/nvim-dap-go#6]
### Feature request
Implement `envFile` attribute in `launch.json` dap configuration.

### Possible profits
A more convenient way to manage dotenvs while debugging complex projects.

### Description
According to VSCode [debugger config](https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes)  there is a very useful attribute `envFile` that helps manage big Dotenv files while debugging complex projects. Without this attribute, there is only one way to use .env files – `env` attribute.
Now it works properly, but after editing variables, we should constantly reload nvim-dap. A workflow like this is painful in my point of view

### Possible solutions
It would be possible to support `envFile` in a nvim-dap extension by using the `enrich_config` hook supported for adapters. See :h dap-adapter
It would need to check if there is a `envFile` property on the config, if so replace it with env with the content from the file and then call on_config with the modified configuration.

**Comment by leoluz** [comment]
It seems this is a feature for https://github.com/yriveiro/dap-go.nvim instead of this one?
Can you please confirm?

**Comment by niklod** [comment]
@leoluz Yep, seems like. I'll ask dap-go.nvim
