### ISSUE TITLE
Simplification of run current test code

### ISSUE THREAD

**Issue by debugloop** [leoluz/nvim-dap-go#62]
Hi, I've recently poked through the code while getting something to work and noticed that the TS logic around running tests has grown quite considerably. I've been using the following snippet for a while now, and I've been wondering if you've ever considered going the LSP route instead of checking treesitter. I think this could at least have some value as an additional backend, but I feel the TS implementation is quite complex really.

```lua
local cursor = vim.api.nvim_win_get_cursor(0)
local lsp_response, lsp_err = vim.lsp.buf_request_sync(0, 'textDocument/documentSymbol',
  { textDocument = vim.lsp.util.make_text_document_params() }, 1000)
if lsp_err == nil then
  for _, symbol in pairs(lsp_response[1].result) do
    if
        symbol.detail:sub(1, 4) == "func" and
        symbol.name:sub(1, 4) == "Test" and
        cursor[1] > symbol.range.start.line and
        cursor[1] < symbol.range["end"].line
    then
      dap.run({
        type = "go",
        name = symbol.name,
        request = "launch",
        mode = "test",
        program = "./" .. vim.fn.fnamemodify(vim.fn.expand("%:.:h"), ":r"),
        args = { "-test.run", "^" .. symbol.name .. "$" },
        buildFlags = "-tags=unit,integration,e2e",
      })
      return
    end
  end
end
```

**Comment by leoluz** [comment]
Hi @debugloop,

I believe that the feature provided as part of this plugin is not supported by what LSP can provide.
The use case is: 
I want to run a *single* test in debug mode regardless of how many nested subtests I have in the code.
Example:

```go
1 func TestFoo(t *testing.T) {
2 	t.Run("Bar", func(t *testing.T) {
3 		assert.Equal(t, 2, 1+3)
4 	})
5 
6 	t.Run("Baz", func(t *testing.T) {
7 		t.Run("Qux", func(t *testing.T) {
8 			assert.Equal(t, 5, 1+3)
9 		})
10	})
11 }
```

If the cursor is in line 8 for example I want to run just that specific subtest and not the whole testcase. As far as I know, `textDocument/documentSymbol` function just returns the top level symbols so this use-case doesn't seem to be possible.

**Comment by debugloop** [comment]
Oh, I never realized that, must have skimmed over that fact in the docs, thanks for clearing that up for me 👍🏻 You're entirely correct that the LSP just gives you the top level tests of course.

I'll have to check how you handle accessing surrounding scope and required setup code run as part of a surrounding test, I'm very curious now 👍🏻 Thanks again 🎉
