### ISSUE TITLE
is it possible to debug test with arguments?

### ISSUE THREAD

**Issue by brunobmello25** [leoluz/nvim-dap-go#64]
similar to the `Debug (arguments)` option, but to run a specific test.

In my usecase, I need to run debug test passing the flag `-tags dynamic` and nvim-dap-go current configurations don't seem to support this

**Comment by Friedrich42** [comment]
I think you can still attach to an existing session, so that may be a workaround

**Comment by leoluz** [comment]
@brunobmello25 You are right. Currently, there is no support to pass flags while running a specific test.
