### ISSUE TITLE
Windows can't not run go dap

### ISSUE THREAD

**Issue by ApolloLhq** [leoluz/nvim-dap-go#66]
why i try to run debug in windows,it always occur "dlv exited with code 2".

**Comment by mkhoatd** [comment]
Me too

**Comment by leoluz** [comment]
Sorry, I am not a Windows user. Someone with Windows would have to investigate.

**Comment by Catalyn45** [comment]
Setting `detached = false` seems to make it work for me, I don't really know why tho.
<img width="375" alt="image" src="https://github.com/leoluz/nvim-dap-go/assets/37979489/7beeee46-85a2-4d0f-a38d-8363163ce5ac">

**Comment by Catalyn45** [comment]
@leoluz Could passing `detached = false` inside the plugin if the OS is windows be a good workaround for the moment? I can try to make a PR if you think this is a good idea.

**Comment by Catalyn45** [comment]
For the moment I think you can workaround it this way
<img width="489" alt="image" src="https://github.com/leoluz/nvim-dap-go/assets/37979489/ccb65cf3-acf1-44c4-b6d2-11b343a80297">

**Comment by leoluz** [comment]
@Catalyn45 Thank you for your PR! Good job updating the documentation. 👍🏻
