### ISSUE TITLE
Help needed to debug go gin project

### ISSUE THREAD

**Issue by h-tiwari-dev** [leoluz/nvim-dap-go#71]
Hi, I need you help to add a configuration to run gin project. I want to run "$ go run ." Is there anyway to run custom commands(like the config we can create in launch.json in vscode). 

Sorry for the noob question, I'm new to neovim and any help is really appreciated.

**Comment by Catalyn45** [comment]
Doesn't the `debug package` configuration work for you? I believe what it does is run `go build .` then starting the resulting executable, basically what `go run .` does under the hood.

**Comment by leoluz** [comment]
@h-tiwari-dev `go run` isn't a good way to debug Go code and it doesn't publish the necessary symbols. Prefer using `go build` whenever possible.
