### ISSUE TITLE
"file not found" error with attach mode

### ISSUE THREAD

**Issue by aj3423** [leoluz/nvim-dap-go#8]
I'm trying to debug with "3: Attach" mode, but it doesn't work and shows error "file not found". My steps:
1. `dlv debug --api-version=2 --headless --listen=:2345`
2. set a breakpoint at line 6 as in the image: `lua require'dap'.toggle_breakpoint()`, the breakpoint sign shows correctly
3. start debugging: `lua require'dap'.continue()`
4. it shows 1~5 options, choose the 3rd "3: Attach"
5. it shows some listening port, choose the one `dlv ... :2345`

Then it shows as image below
![image](https://user-images.githubusercontent.com/4710875/171922754-73d5538b-d653-4c47-9dcb-61d3ef4053fc.png)

It doesn't break at that line and I cannot continue it.
It shows file "/e/go/src/a.j/aj/3/3.go" not found, but the file does exist, it's the file at top-right buffer. 

How to fix it?

**Comment by leoluz** [comment]
Sorry for the delay answering you.
One of main points about using the plugin is not having to run dlv manually. 

If all you want is to debug the main, add the breakpoint and choose the option to debug the main function. You don't need to attach in this case.

**Comment by aj3423** [comment]
@leoluz Sorry I should have used the real application as demo, which is based on cli and somehow it does not work with direct debugging, I have to use the attach mode. It's like:
```golang
package main

import (
	"fmt"

	"github.com/c-bata/go-prompt"
)

func completer(in prompt.Document) []prompt.Suggest {
	return nil
}
func executor(in string) {}

func main() {
	a := 2
	fmt.Println(a) // <------  set a breakpoint here, same error on attach: "could not find file..."

	p := prompt.New(
		executor,
		completer,
		prompt.OptionPrefix(">>> "),
	)
	p.Run()
}
```

**Comment by leoluz** [comment]
I am unable to build this application with this library. 
If I do:
`go build debug/main.go`
I get:
```
# golang.org/x/sys/unix
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200918174421-af09f7315aff/unix/syscall_darwin.1_13.go:29:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200918174421-af09f7315aff/unix/zsyscall_darwin_amd64.1_13.go:27:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200918174421-af09f7315aff/unix/zsyscall_darwin_amd64.1_13.go:40:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200918174421-af09f7315aff/unix/zsyscall_darwin_amd64.go:28:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200918174421-af09f7315aff/unix/zsyscall_darwin_amd64.go:43:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200918174421-af09f7315aff/unix/zsyscall_darwin_amd64.go:59:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200918174421-af09f7315aff/unix/zsyscall_darwin_amd64.go:75:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200918174421-af09f7315aff/unix/zsyscall_darwin_amd64.go:90:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200918174421-af09f7315aff/unix/zsyscall_darwin_amd64.go:105:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200918174421-af09f7315aff/unix/zsyscall_darwin_amd64.go:121:3: //go:linkname must refer to declared function or variable
../../go/pkg/mod/golang.org/x/sys@v0.0.0-20200918174421-af09f7315aff/unix/zsyscall_darwin_amd64.go:121:3: too many errors
```
Maybe this lib is just for linux?

**Comment by aj3423** [comment]
@leoluz  I have no experience with Mac, maybe just use a simple helloworld, which also causes the problem "could not find file ...":
```golang
package main

import (
	"fmt"
)

func main() {
	a := 2  // <---- set a breakpoint here
	fmt.Println(a)
}
```

**Comment by leoluz** [comment]
I am sorry but I don't understand why you are trying to attach using (option 3). You can just add a breakpoint and select option 1 (Debug) and it will work.

**Comment by aj3423** [comment]
I use attach(option 3) because my real app depends on the ‘go-prompt‘ library. With that library, I can't simply add break and debug with option 1, it crashes. The dlv debugger is also cli application, so debug a cli app with cli debugger, maybe somehow it causes the crash. So I want to try if it works with attach mode(option3).
But since the ‘go-prompt‘ library doesn‘t work on Mac, a hello world application is enough for reproducing the problem. I think if I can “attach debug“ the helloworld app, I should also be able to “attach debug“ my real cli app.

**Comment by leoluz** [comment]
Keep in mind that to attach you need the pid of the running process. You shouldn't be attaching to delve. You need to attach to your running program. If the program already concluded when you are trying to debug there won't be any process to attach to.

I hope this helps clarifying the issue you are having.

**Comment by aj3423** [comment]
Thanks, I see now there is new "attach remote" config, which solves this problem.
