### ISSUE TITLE
Support custom adapter config

### ISSUE THREAD

**Issue by YogiPristiawan** [leoluz/nvim-dap-go#83]
Hi,

i want to load my custom config bellow

```
  dap.adapters.custom = {
    type = "server",
    host = "127.0.0.1",
    port = 2345,
  }
```

but the plugins only support the `go` adapter type

**Comment by leoluz** [comment]
Hi @YogiPristiawan,

This project is mainly a Go extension for the nvim-dap plugin. I am not sure what is the intention with custom adapter. Which use cases are you willing to cover with this proposal?

**Comment by YogiPristiawan** [comment]
Because I have constraints when using the defined go adapters configurations:

- I can't use a debugger if my main package is not in the root directory. Therefore, I can't use debug_test.
- I want to connect to my running delve instance that runs together with [Air](https://github.com/cosmtrek/air). I run my project using [Air](https://github.com/cosmtrek/air) because I need hot reload for local development, and I also need to load my .env file.
